-- Seed: dados iniciais do cardápio (convertido de data/data.json)
-- Histórico: as imagens apontam para assets/img/ e devem ser migradas para o Supabase Storage.

INSERT INTO public.sections (id, title, type, "order", items) VALUES
  ('entradas', 'Entradas', 'food', 0, '[{"name":"Bolinhos de bacalhau (8 unid. - molho tártaro)","description":null,"price":"R$ 31,90","image":"assets/img/Bolinho de bacalhau.jpeg","available":true},{"name":"Pastel de queijo (8 unid.)","description":null,"price":"R$ 24,90","image":null,"available":true},{"name":"Pastel de camarão (8 unid.)","description":null,"price":"R$ 25,60","image":null,"available":true},{"name":"Pastel de carne de sol acebolada (8 unid.)","description":null,"price":"R$ 25,10","image":null,"available":true},{"name":"Salada de frango (molho mostarda)","description":null,"price":"R$ 25,90","image":null,"available":true},{"name":"Salada de camarão (molho caesar)","description":null,"price":"R$ 28,90","image":null,"available":true}]'::jsonb),
  ('prato-principal', 'Prato Principal', 'food', 1, '[{"name":"Picanha ao molho de ervas (arroz com brócolis, batata frita, farofa de biscoito)","description":null,"price":"R$ 62,00","image":"assets/img/Picanha molho de ervas.jpeg","available":true},{"name":"Filé mignon com molho poivre e risoto de queijo e farofa","description":null,"price":"R$ 64,90","image":"assets/img/Filé mignon com molho poivre e risoto de queijo e farofa.jpeg","available":true},{"name":"Filé mignon (arroz piamontese, aipim frito e molho de mostarda)","description":null,"price":"R$ 59,80","image":"assets/img/Fl com molho de mostarda.jpeg","available":true},{"name":"Paillard de filé mignon (Fettuccine, molho de queijo)","description":null,"price":"R$ 41,90","image":"assets/img/Paillard.jpeg","available":true},{"name":"Filé à milanesa (purê de batata, arroz com cenoura)","description":null,"price":"R$ 39,90","image":"assets/img/Filé à milanesa.jpeg","available":true},{"name":"Parmegiana de carne (talharim na manteiga, com ervas, e molho de tomate e mussarela)","description":null,"price":"R$ 41,70","image":"assets/img/Parmegiana.jpeg","available":true},{"name":"Peixe grelhado (purê, arroz de brócolis, molho de cebola roxa)","description":null,"price":"R$ 42,90","image":"assets/img/Peixe grelhado.jpeg","available":true},{"name":"Moqueca com camarão e peixe (arroz de coentro, farofa de dendê)","description":null,"price":"R$ 47,80","image":"assets/img/Muqueca de peixe com camarão.jpeg","available":true},{"name":"Bobó de camarão (arroz branco, farofa de biscoito)","description":null,"price":"R$ 44,90","image":"assets/img/Bobó de camarão.jpeg","available":true},{"name":"Risoto de camarão (molho bisque de de camarão e queijo)","description":null,"price":"R$ 52,90","image":"assets/img/Risoto de camarão.jpeg","available":true},{"name":"Espaguete com camarão (molho de tomate confit)","description":null,"price":"R$ 44,30","image":"assets/img/Espaguete de camarão massa fresca.jpeg","available":true},{"name":"Peixe a milanesa (arroz piamontese, mix de folhas, molho de ervas)","description":null,"price":"R$ 47,30","image":null,"available":true},{"name":"Peito de frango grelhado (arroz de brócolis, aipim frito ao molho de mostarda)","description":null,"price":"R$ 31,90","image":null,"available":true},{"name":"Frango desfiado ao molho de queijo (arroz branco, batata palha)","description":null,"price":"R$ 29,90","image":"assets/img/Frango desfiado com molho de queijo.jpeg","available":true},{"name":"Frango crocante temperado com ervas , arrroz de cenoura e mix de folhas","description":null,"price":"R$ 28,90","image":"assets/img/Fg crocante.jpeg","available":true}]'::jsonb),
  ('massas', 'Massas', 'food', 2, '[{"name":"Ravioli de queijo com ervas e molho de tomate","description":null,"price":"R$ 31,80","image":"assets/img/Ravioli de queijo.jpeg","available":true},{"name":"Ravioli de ragu com linguiça e carne com molho de tomate","description":null,"price":"R$ 32,60","image":"assets/img/Ravioli de ragu.jpeg","available":true},{"name":"Fettuccine ao ragu de linguiça e carne com molho de tomate","description":null,"price":"R$ 30,30","image":"assets/img/Fettuccine com ragu.jpeg","available":true},{"name":"Nhoque de batata com ragu de com molho de tomate","description":null,"price":"R$ 28,90","image":null,"available":true}]'::jsonb),
  ('prato-crianca', 'Prato de Criança', 'food', 3, '[{"name":"Carne ou frango (arroz branco, batata frita e feijão)","description":null,"price":"R$ 22,00","image":"assets/img/Fg infantil.jpeg","available":true}]'::jsonb),
  ('guarnicao', 'Guarnição', 'food', 4, '[{"name":"Rubacão com feijão branco","description":null,"price":"R$ 16,00","image":null,"available":true},{"name":"Batata frita","description":null,"price":"R$ 15,00","image":null,"available":true},{"name":"Arroz branco","description":null,"price":"R$ 8,00","image":null,"available":true},{"name":"Arroz com brócolis","description":null,"price":"R$ 12,00","image":null,"available":true},{"name":"Feijão","description":null,"price":"R$ 5,00","image":null,"available":true},{"name":"Farofa de ovos","description":null,"price":"R$ 10,00","image":null,"available":true}]'::jsonb),
  ('sobremesa', 'Sobremesa', 'food', 5, '[{"name":"Delícia de banana (sorvete, calda de caramelo)","description":null,"price":"R$ 9,00","image":"assets/img/Delícia de banana.jpeg","available":true},{"name":"Brownie (sorvete, calda de chocolate)","description":null,"price":"R$ 11,00","image":"assets/img/Brownie.jpeg","available":true},{"name":"Cheesecake","description":null,"price":"R$ 9,00","image":"assets/img/Cheesecake.jpeg","available":true},{"name":"Pudim de leite","description":null,"price":"R$ 8,00","image":"assets/img/Pudim.jpeg","available":true}]'::jsonb),
  ('cafe', 'Café', 'drinks', 6, '[{"name":"Café expresso","description":null,"price":"R$ 4,00","image":null,"available":true},{"name":"Capuccino","description":null,"price":"R$ 7,00","image":null,"available":true}]'::jsonb),
  ('drink', 'Drink', 'drinks', 7, '[{"name":"Drink tardinha","description":"(Gengibre, limão, polpa de maracujá, xarope de açúcar, gelo, cachaça)","price":"R$ 26,00","image":null,"available":true},{"name":"Drink Espanhola","description":null,"price":"R$ 23,00","image":null,"available":true},{"name":"Aperol ice","description":"(Gelo, laranja, aperol, lecce)","price":"R$ 22,90","image":null,"available":true},{"name":"Espaguete","description":"(Aperol, gelo, limão, cerveja)","price":"R$ 23,90","image":null,"available":true},{"name":"Aperol tônica","description":"(Gelo, maracujá, aperol, água tônica)","price":"R$ 24,00","image":"assets/img/Aperol água tônica.jpeg","available":true},{"name":"Campari isotônico","description":"(Gelo, campari, gatorade de laranja)","price":"R$ 25,50","image":null,"available":true},{"name":"Campari ice","description":"(Gelo, limão, campari e ice)","price":"R$ 24,90","image":null,"available":true},{"name":"Cubra libre","description":"(Rum, limão e Coca-Cola)","price":"R$ 23,00","image":null,"available":true}]'::jsonb),
  ('coquetel', 'Coquetel', 'drinks', 8, '[{"name":"Caipirinha","description":"(Cachaça, limão, xarope de açúcar e gelo)","price":"R$ 16,00","image":"assets/img/Caipirinha.jpeg","available":true},{"name":"Caipivodka","description":"(Vodka, limão, xarope de açúcar e gelo)","price":"R$ 21,00","image":"assets/img/Capi vodkade maracujá.jpeg","available":true},{"name":"Pina colada","description":"(Abacaxi, leite de coco, leite condensado, gelo e vodka)","price":"R$ 24,00","image":"assets/img/Pina colanda.jpeg","available":true}]'::jsonb),
  ('vinho-branco', 'Vinho Branco', 'drinks', 9, '[{"name":"Rose Roncher toro reservado suave - Chileno","description":null,"price":"R$ 94,00","image":null,"available":true},{"name":"Frisanto Sprinter - Chileno","description":"(Branco doce)","price":"R$ 87,00","image":null,"available":true}]'::jsonb),
  ('vinho-tinto', 'Vinho Tinto', 'drinks', 10, '[{"name":"Explorador - Chileno","description":"(Merlot, tinto seco)","price":"R$ 99,00","image":null,"available":true},{"name":"Cosecha - Chileno","description":"(Tarapaca, cabernet, meio seco)","price":"R$ 95,00","image":null,"available":true},{"name":"Chilano - Chileno","description":"(Carmenere, tinto seco)","price":"R$ 90,00","image":null,"available":true},{"name":"G7 - Chileno","description":"(Carmenère, Tinto seco)","price":"R$ 71,00","image":null,"available":true},{"name":"G7 - Cabernere Sauvignon - Chileno","description":"(Tinto seco)","price":"R$ 71,00","image":null,"available":true},{"name":"Di Mallo - Uruguai","description":"(Tinto seco)","price":"R$ 102,00","image":null,"available":true},{"name":"Toro Cabernet Sauvignon - Argentino","description":"(Centenário meio seco)","price":"R$ 89,00","image":null,"available":true}]'::jsonb),
  ('Rum', 'Rum', 'drinks', 11, '[{"name":"Bacardi - Carta Prata","description":null,"price":"R$ 12,00","image":null,"available":true},{"name":"Bacardi - Carta Ouro","description":null,"price":"R$ 12,00","image":null,"available":true},{"name":"Montilla - Carta Ouro","description":null,"price":"R$ 10,00","image":null,"available":true},{"name":"Montilla - Carta Cristal","description":null,"price":"R$ 10,00","image":null,"available":true}]'::jsonb),
  ('Aguardente', 'Aguardente', 'drinks', 12, '[{"name":"Ypióca s/palha ouro","description":null,"price":"R$ 8,00","image":null,"available":true},{"name":"Rainha","description":null,"price":"R$ 8,00","image":null,"available":true},{"name":"Serra Limpa","description":null,"price":"R$ 10,00","image":null,"available":true},{"name":"Matuta","description":null,"price":"R$ 8,00","image":null,"available":true}]'::jsonb),
  ('Conhaque', 'Conhaque', 'drinks', 13, '[{"name":"Domecq","description":null,"price":"R$ 12,00","image":null,"available":true},{"name":"Dreher","description":null,"price":"R$ 8,00","image":null,"available":true},{"name":"Alcatrão","description":null,"price":"R$ 7,00","image":null,"available":true},{"name":"Vinho Porto","description":null,"price":"R$ 14,00","image":null,"available":true}]'::jsonb),
  ('Cerveja-Long-Neck', 'Cerveja - Long Neck', 'drinks', 14, '[{"name":"Heineken","description":null,"price":"R$ 10,50","image":null,"available":true},{"name":"Spaten","description":null,"price":"R$ 10,00","image":null,"available":true},{"name":"Eisenbahn","description":null,"price":"R$ 9,90","image":null,"available":true},{"name":"Stella Artois","description":null,"price":"R$ 10,00","image":null,"available":true}]'::jsonb),
  ('cerveja-lata', 'Cerveja - Lata', 'drinks', 15, '[{"name":"Budweiser","description":null,"price":"R$ 9,20","image":null,"available":true},{"name":"Amstel","description":null,"price":"R$ 8,50","image":null,"available":true},{"name":"Puro Malte","description":null,"price":"R$ 8,00","image":null,"available":true}]'::jsonb),
  ('espumante', 'Espumante', 'drinks', 16, '[{"name":"Salton","description":null,"price":"R$ 99,00","image":"assets/img/Espumante Salton.jpeg","available":true},{"name":"Brasil","description":null,"price":"[Preço Vazio]","image":null,"available":true},{"name":"Chandon Brut","description":null,"price":"R$ 145,00","image":"assets/img/Espumante Chandon.jpeg","available":true},{"name":"Serra Gaúcha","description":null,"price":"[Preço Vazio]","image":null,"available":true}]'::jsonb),
  ('destilada', 'Destilada', 'drinks', 17, '[{"name":"Gin","description":null,"price":"R$ 14,00","image":null,"available":true},{"name":"Tequila","description":null,"price":"R$ 12,00","image":null,"available":true}]'::jsonb),
  ('licor', 'Licor', 'drinks', 18, '[{"name":"Marula","description":null,"price":"R$ 11,00","image":null,"available":true},{"name":"Amaretto","description":null,"price":"R$ 11,20","image":null,"available":true}]'::jsonb),
  ('refrigerante', 'Refrigerante', 'drinks', 19, '[{"name":"Coca-Cola lata 350ml","description":null,"price":"R$ 5,80","image":null,"available":true},{"name":"Coca-Cola Zero lata 350ml","description":null,"price":"R$ 5,80","image":null,"available":true},{"name":"Guaraná Antártica lata 350ml","description":null,"price":"R$ 5,10","image":null,"available":true},{"name":"Fanta laranja lata 350ml","description":null,"price":"R$ 5,20","image":null,"available":true},{"name":"Fanta uva lata 350ml","description":null,"price":"R$ 5,20","image":null,"available":true},{"name":"Pepsi lata 350ml","description":null,"price":"R$ 5,10","image":null,"available":true},{"name":"H2O Limonete 500ml","description":null,"price":"R$ 8,00","image":null,"available":true},{"name":"Red Bull 250ml","description":null,"price":"R$ 12,00","image":null,"available":true},{"name":"Água tônica 350ml","description":null,"price":"R$ 5,50","image":null,"available":true},{"name":"Água mineral com gás 500ml","description":null,"price":"R$ 3,00","image":null,"available":true}]'::jsonb),
  ('bebida-mista', 'Bebida Mista', 'drinks', 20, '[{"name":"Cítrus 330ml","description":null,"price":"R$ 5,00","image":null,"available":true},{"name":"Gatorade 500ml","description":null,"price":"R$ 12,00","image":null,"available":true}]'::jsonb),
  ('suco', 'Suco', 'drinks', 21, '[{"name":"Laranja","description":null,"price":"R$ 6,10","image":null,"available":true},{"name":"Limonada","description":null,"price":"R$ 4,90","image":null,"available":true},{"name":"Suco da fruta (Temporada)","description":null,"price":"R$ 5,00","image":null,"available":true}]'::jsonb),
  ('whisky', 'Whisky', 'drinks', 22, '[{"name":"Black Label","description":null,"price":"R$ 16,00","image":null,"available":true},{"name":"Write Horse","description":null,"price":"R$ 14,00","image":null,"available":true},{"name":"Jack Daniels","description":null,"price":"R$ 16,00","image":null,"available":true},{"name":"Ballantines","description":null,"price":"R$ 10,00","image":null,"available":true},{"name":"Red Label","description":null,"price":"R$ 11,00","image":null,"available":true}]'::jsonb),
  ('vodka', 'Vodka', 'drinks', 23, '[{"name":"Sminorff","description":null,"price":"R$ 10,00","image":null,"available":true},{"name":"Absolut","description":null,"price":"R$ 11,00","image":null,"available":true},{"name":"Dallof","description":null,"price":"R$ 10,00","image":null,"available":true}]'::jsonb);
